version: "3.8"
services:

  flask_service:
    build:
      context: ../../shared/flask
    image: flask_service:python-3.10-slim-bullseye
    restart: "no"
    deploy:
      replicas: 0

  front-envoy:
    build:
      context: .
      dockerfile: Dockerfile-frontenvoy
    depends_on:
      backend-service:
        condition: service_healthy
    ports:
    - "${PORT_BACKEND:-8002}:10000"
    - "${PORT_STATS:-8003}:8001"

  backend-service:
    build:
      context: ../../shared/service
    volumes:
    - ./service.py:/code/service.py
