services:

  proxy:
    build:
      dockerfile: ../shared/envoy/Dockerfile
      target: envoy-certs
    ports:
    - "${PORT_PROXY:-10000}:10000"

  proxy-client:
    build:
      dockerfile: ../shared/envoy/Dockerfile
      target: envoy-certs
      args:
        ENVOY_CONFIG: envoy-client.yaml
    ports:
    - "${PORT_PROXY_CLIENT:-20000}:10000"

  http-upstream1:
    build:
      dockerfile: Dockerfile-echo
    hostname: http-upstream1
    environment:
    - HTTPS_PORT=0

  http-upstream2:
    build:
      dockerfile: Dockerfile-echo
    hostname: http-upstream2
    environment:
    - HTTPS_PORT=0

  https-upstream3:
    build:
      dockerfile: Dockerfile-echo
    hostname: https-upstream3
    environment:
    - HTTP_PORT=0
