version: "3.8"
services:

  proxy:
    build:
      context: .
      dockerfile: Dockerfile-proxy
    ports:
    - "${PORT_PROXY:-1999}:1999"
    - "${PORT_ADMIN:-8001}:8001"

  redis:
    build:
      context: .
      dockerfile: Dockerfile-redis
