# This build environment follows the one maintained by SRE team in the Envoy RPM spec:
# https://github.com/xgen-cloud/rpm-spec/blob/master/build/envoy/SPECS/envoy.spec
FROM amazonlinux:2

RUN amazon-linux-extras install epel
RUN yum groupinstall -y 'Development Tools'
RUN yum install -y clang python3
RUN yum install -y libstdc++-static cmake3 llvm llvm-devel python3-pip pprof
RUN yum install -y aspell-en libatomic libstdc++ libtool which xz

RUN ln -sf $(which cmake3) /usr/local/bin/cmake

# To build wee8 we need ninja version >= 1.8.2.
# wee8 contains such binaries in the third_party but not for aarch64.
# So it will fall back to the system ninja and not work properly.
ARG NINJA_DIR="ninja-1.8.2"
ARG NINJA_URL="https://github.com/ninja-build/ninja/archive/refs/tags/v1.8.2.tar.gz"
RUN curl -L ${NINJA_URL} -OJ && tar xf ${NINJA_DIR}.tar.gz && python ./${NINJA_DIR}/configure.py --bootstrap && mv ninja /usr/local/bin

# For some reason all of LLVM except lld exists on al2
ARG LLD_DIR="lld-11.1.0.src"
ARG LLD_URL="https://github.com/llvm/llvm-project/releases/download/llvmorg-11.1.0/${LLD_DIR}.tar.xz"
RUN curl -L ${LLD_URL} -OJ && tar xf ${LLD_DIR}.tar.xz && cmake3 -GNinja -S ./${LLD_DIR} -B ./lld && ninja -C ./lld && ln -sfr ./lld/bin/* /usr/local/bin

# Install bazel
ARG BAZEL_URL="https://github.com/bazelbuild/bazelisk/releases/download/v1.9.0/bazelisk-linux-arm64"
RUN curl -L -o /usr/local/bin/bazel ${BAZEL_URL} && chmod +x /usr/local/bin/bazel

# Silence the error that git detected dubious ownership in repository.
RUN git config --global --add safe.directory '*'
