services:

  tls-inspector:
    build:
      dockerfile: ../shared/envoy/Dockerfile
    depends_on:
      service-https-http2:
        condition: service_started
      service-https-http1.1:
        condition: service_started
      service-http:
        condition: service_started
    ports:
    - "${PORT_PROXY:-10000}:10000"
    - "${PORT_ADMIN:-12345}:12345"

  service-https-http2:
    build:
      dockerfile: Dockerfile-echo
    hostname: service-https-http2
    environment:
    - HTTP_PORT=0

  service-https-http1.1:
    build:
      dockerfile: Dockerfile-echo
    hostname: service-https-http1.1
    environment:
    - HTTP_PORT=0

  service-http:
    build:
      dockerfile: Dockerfile-echo
    hostname: service-http
    environment:
    - HTTPS_PORT=0
