
parameters:

- name: bucketGCP
  type: string
  default: ""

## Timeouts
# Workaround for https://github.com/envoyproxy/envoy/issues/26634
- name: timeoutDockerPublish
  displayName: "Timout Docker publish"
  type: number
  # in seconds
  default: 15
- name: timeoutDockerBuild
  displayName: "Timout Docker build"
  type: number
  default: 400

# Auth
- name: authGCP
  type: string
  default: ""
- name: authGithubWorkflow
  type: string
  default: ""
- name: authGithubWorkflowAppId
  type: string
  default: ""
- name: authGithubWorkflowInstallId
  type: string
  default: ""
- name: authGPGPassphrase
  type: string
  default: ""
- name: authGPGPath
  type: string
  default: ""
- name: authGPGKey
  type: string
  default: ""
- name: authNetlifyURL
  type: string
  default: ""
- name: authDockerUser
  type: string
  default: ""
- name: authDockerPassword
  type: string
  default: ""
- name: authSSHDocsKey
  type: string
  default: ""
- name: authSSHDocsKeyPublic
  type: string
  default: ""
- name: authSSHKeyPassphrase
  type: string
  default: ""

- name: runDocker
  displayName: "Run Docker"
  type: string
  default: true
- name: runPackaging
  displayName: "Run Packaging"
  type: string
  default: true

- name: publishDockerhub
  displayName: "Publish Dockerhub"
  type: string
  default: false
- name: publishDocs
  displayName: "Publish Docs"
  type: string
  default: false
- name: publishDocsLatest
  displayName: "Publish latest docs"
  type: string
  default: false
- name: publishDocsRelease
  displayName: "Publish release docs"
  type: string
  default: false
- name: publishGithubRelease
  displayName: "Publish Github release"
  type: string
  default: false

jobs:
- job: docker
  displayName: "Docker (Linux multi arch)"
  condition: |
    and(not(canceled()),
        eq(${{ parameters.runDocker }}, 'true'))
  timeoutInMinutes: 120
  pool:
    vmImage: $(agentUbuntu)
  steps:
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: current
      artifactName: "bazel.release"
      itemPattern: "bazel.release/**/bin/*"
      targetPath: $(Build.StagingDirectory)
  - template: ../bazel.yml
    parameters:
      ciTarget: docker-upload
      publishEnvoy: false
      publishTestResults: false
      pathDockerBind: ""
      cacheKeyDocker: "$(cacheKeyDockerBuild)"
      cacheKeyVersion: "$(cacheKeyDockerBuildVersion)"
      pathCacheTemp: /var/azpcache
      tmpfsCacheDisabled: true
      diskspaceHack: true
      env:
        GCS_ARTIFACT_BUCKET: ${{ parameters.bucketGCP }}
      stepsPre:
      - bash: |
          echo "disk space at beginning of Docker build:"
          df -h
        displayName: "Check disk space before Docker build"
      - bash: |
          set -e

          mkdir -p linux/amd64 linux/arm64

          # x64
          cp -a $(Build.StagingDirectory)/bazel.release/x64/bin/release.tar.zst linux/amd64/release.tar.zst
          cp -a $(Build.StagingDirectory)/bazel.release/x64/bin/schema_validator_tool linux/amd64/schema_validator_tool

          # arm64
          cp -a $(Build.StagingDirectory)/bazel.release/arm64/bin/release.tar.zst linux/arm64/release.tar.zst
          cp -a $(Build.StagingDirectory)/bazel.release/arm64/bin/schema_validator_tool linux/arm64/schema_validator_tool

          # Debug what files appear to have been downloaded
          find linux -type f -name "*" | xargs ls -l

          ci/docker_ci.sh
        displayName: Build Docker images
        timeoutInMinutes: ${{ parameters.timeoutDockerPublish }}
        workingDirectory: $(Build.SourcesDirectory)
        env:
          AZP_BRANCH: $(Build.SourceBranch)
          AZP_SHA1: $(Build.SourceVersion)
          DOCKERHUB_USERNAME: ${{ parameters.authDockerUser }}
          DOCKERHUB_PASSWORD: ${{ parameters.authDockerPassword }}
          DOCKER_BUILD_TIMEOUT: ${{ parameters.timeoutDockerBuild }}
      stepsPost:
      - script: |
          set -e
          sudo .azure-pipelines/docker/save_cache.sh /var/azpcache/docker true
          sudo rm -rf /var/lib/docker
        displayName: "Cache/save (publish_docker)"
        condition: and(succeeded(), ne(variables.DOCKER_CACHE_RESTORED, 'true'))

- job: package_x64
  displayName: Linux debs (x64)
  dependsOn: []
  condition: |
    and(not(canceled()),
        eq(${{ parameters.runPackaging }}, 'true'))
  timeoutInMinutes: 120
  pool:
    vmImage: $(agentUbuntu)
  steps:
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: current
      artifactName: "bazel.release"
      itemPattern: "bazel.release/x64/bin/*"
      targetPath: $(Build.StagingDirectory)
  - template: ../bazel.yml
    parameters:
      ciTarget: bazel.distribution
      publishTestResults: false
      stepsPre:
      - template: ../gpg.yml
        parameters:
          authGPGPassphrase: ${{ parameters.authGPGPassphrase }}
          authGPGPath: ${{ parameters.authGPGPath }}
          authGPGKey: ${{ parameters.authGPGKey }}
          pathGPGConfiguredHome: /build/.gnupg
          pathGPGHome: $(Build.StagingDirectory)/.gnupg
      stepsPost:
      - bash: |
          set -e
          rm -rf $(Build.StagingDirectory)/.gnupg

- job: package_arm64
  displayName: Linux debs (arm64)
  dependsOn: []
  condition: |
    and(not(canceled()),
        eq(${{ parameters.runPackaging }}, 'true'))
  timeoutInMinutes: 120
  pool: "envoy-arm-small"
  steps:
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: current
      artifactName: "bazel.release"
      itemPattern: "bazel.release/arm64/bin/*"
      targetPath: $(Build.StagingDirectory)

  - template: ../bazel.yml
    parameters:
      managedAgent: false
      ciTarget: bazel.distribution
      rbe: false
      artifactSuffix: ".arm64"
      bazelBuildExtraOptions: "--sandbox_base=/tmp/sandbox_base"
      publishTestResults: false
      tmpfsDockerDisabled: true
      stepsPre:
      - template: ../gpg.yml
        parameters:
          authGPGPassphrase: ${{ parameters.authGPGPassphrase }}
          authGPGPath: ${{ parameters.authGPGPath }}
          authGPGKey: ${{ parameters.authGPGKey }}
          pathGPGConfiguredHome: /build/.gnupg
          pathGPGHome: $(Build.StagingDirectory)/.gnupg
      stepsPost:
      - bash: |
          set -e
          rm -rf $(Build.StagingDirectory)/.gnupg

- job: docs
  displayName: Publish docs
  dependsOn: []
  condition: |
    and(not(canceled()),
        eq(${{ parameters.publishDocs }}, 'true'))
  pool:
    vmImage: $(agentUbuntu)
  steps:
  - template: ../bazel.yml
    parameters:
      ciTarget: docs
      cacheVersion: $(cacheKeyBazel)
      publishEnvoy: false
      publishTestResults: false
      env:
        AZP_BRANCH: $(Build.SourceBranch)
      stepsPost:

      - script: |
          ci/run_envoy_docker.sh 'ci/do_ci.sh dockerhub-publish'
        condition: |
          and(not(canceled()),
              eq(${{ parameters.publishDockerhub }}, 'true'))
        displayName: "Publish Dockerhub description and README"
        env:
          ENVOY_DOCKER_BUILD_DIR: $(Build.StagingDirectory)
          ENVOY_RBE: "1"
          BAZEL_BUILD_EXTRA_OPTIONS: "--config=remote-ci --config=rbe-google --jobs=$(RbeJobs)"
          GCP_SERVICE_ACCOUNT_KEY: ${{ parameters.authGCP }}
          GCS_ARTIFACT_BUCKET: ${{ parameters.bucketGCP }}
          DOCKERHUB_USERNAME: ${{ parameters.authDockerUser }}
          DOCKERHUB_PASSWORD: ${{ parameters.authDockerPassword }}

      # Trigger Netlify rebuild of latest docs
      - script: |
          ci/run_envoy_docker.sh 'ci/do_ci.sh docs-upload'
        displayName: "Upload Docs to GCS"
        condition: |
          and(not(canceled()),
              eq(${{ parameters.publishDocsLatest }}, 'true'))
        env:
          ENVOY_DOCKER_BUILD_DIR: $(Build.StagingDirectory)
          ENVOY_RBE: "1"
          BAZEL_BUILD_EXTRA_OPTIONS: "--config=remote-ci --config=rbe-google --jobs=$(RbeJobs)"
          GCP_SERVICE_ACCOUNT_KEY: ${{ parameters.authGCP }}
          GCS_ARTIFACT_BUCKET: ${{ parameters.bucketGCP }}
      - script: ci/run_envoy_docker.sh 'ci/do_ci.sh docs-publish-latest'
        condition: |
          and(not(canceled()),
              eq(${{ parameters.publishDocsLatest }}, 'true'))
        displayName: "Publish latest docs"
        workingDirectory: $(Build.SourcesDirectory)
        env:
          NETLIFY_TRIGGER_URL: ${{ parameters.authNetlifyURL }}

      # Publish docs to the website
      - task: InstallSSHKey@0
        condition: |
          and(not(canceled()),
              eq(${{ parameters.publishDocsRelease }}, 'true'))
        inputs:
          hostName: $(authGithubSSHKeyPublic)
          sshPublicKey: "${{ parameters.authSSHDocsKeyPublic }}"
          sshPassphrase: "${{ parameters.authSSHKeyPassphrase }}"
          sshKeySecureFile: "${{ parameters.authSSHDocsKey }}"
      - script: docs/publish.sh
        condition: |
          and(not(canceled()),
              eq(${{ parameters.publishDocsRelease }}, 'true'))
        displayName: "Publish release docs"
        workingDirectory: $(Build.SourcesDirectory)

- job: signed_release
  displayName: Signed binaries
  dependsOn:
  - package_x64
  - package_arm64
  condition: |
    and(succeeded(),
        eq(${{ parameters.runPackaging }}, 'true'))
  timeoutInMinutes: 120
  pool:
    vmImage: $(agentUbuntu)
  steps:
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: current
      artifactName: "bazel.release"
      itemPattern: "bazel.release/**/bin/*"
      targetPath: $(Build.StagingDirectory)
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: current
      artifactName: "bazel.distribution"
      itemPattern: "bazel.distribution/**/packages.*.tar.gz"
      targetPath: $(Build.StagingDirectory)
  - template: ../bazel.yml
    parameters:
      ciTarget: release.signed
      publishTestResults: false
      env:
        GCS_ARTIFACT_BUCKET: ${{ parameters.bucketGCP }}
      stepsPre:
      - template: ../gpg.yml
        parameters:
          authGPGPassphrase: ${{ parameters.authGPGPassphrase }}
          authGPGPath: ${{ parameters.authGPGPath }}
          authGPGKey: ${{ parameters.authGPGKey }}
          pathGPGConfiguredHome: /build/.gnupg
          pathGPGHome: $(Build.StagingDirectory)/.gnupg
- job: success
  dependsOn: ["docker", "docs", "signed_release"]
  displayName: Success (linux artefacts)
  pool:
    vmImage: $(agentUbuntu)
  # This condition ensures that this (required) check passes if all of
  # the preceding checks either pass or are skipped
  # adapted from:
  #   https://learn.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#job-to-job-dependencies-within-one-stage
  condition: |
    and(
      in(dependencies.docker.result, 'Succeeded', 'SucceededWithIssues', 'Skipped'),
      in(dependencies.docs.result, 'Succeeded', 'SucceededWithIssues', 'Skipped'),
      in(dependencies.signed_release.result, 'Succeeded', 'SucceededWithIssues', 'Skipped'))
  steps:
  - checkout: none
  - bash: |
      echo "building publishable assets complete"

- job: github
  displayName: Publish release tag
  dependsOn: ["success"]
  condition: |
    and(not(canceled()),
        in(dependencies.success.result, 'Succeeded', 'SucceededWithIssues'),
        eq(${{ parameters.publishGithubRelease }}, 'true'))
  pool:
    vmImage: $(agentUbuntu)
  steps:
  - template: ../bazel.yml
    parameters:
      ciTarget: verify.trigger
      authGithub: "$(key.value)"
      cacheVersion: $(cacheKeyBazel)
      publishEnvoy: false
      publishTestResults: false
      env:
        ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
          ENVOY_HEAD_REF: "$(Build.SourceBranch)"
          ENVOY_BRANCH: "$(System.PullRequest.TargetBranch)"
          ENVOY_COMMIT: "$(System.PullRequest.SourceCommitId)"
        ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
          ENVOY_HEAD_REF: "$(Build.SourceBranchName)"
          ENVOY_BRANCH: "$(Build.SourceBranch)"
        # github auth
        GITHUB_APP_ID: ${{ parameters.authGithubWorkflowAppId }}
        GITHUB_INSTALL_ID: ${{ parameters.authGithubWorkflowInstallId }}
        # rbe env
        GCS_ARTIFACT_BUCKET: ${{ parameters.bucketGCP }}
      stepsPre:
      - bash: |
          set -e
          if [[ "$BUILD_REASON" == "PullRequest" ]]; then
              DOWNLOAD_PATH="$(git rev-parse HEAD | head -c7)"
          else
              DOWNLOAD_PATH="${SYSTEM_PULLREQUEST_PULLREQUESTNUMBER:-${BUILD_SOURCEBRANCHNAME}}"
          fi
          curl -sLO "https://storage.googleapis.com/${{ parameters.bucketGCP }}/${DOWNLOAD_PATH}/release/release.signed.tar.zst"
          mkdir -p $(Build.StagingDirectory)/release.signed
          mv release.signed.tar.zst $(Build.StagingDirectory)/release.signed
        displayName: Fetch signed release
      - task: DownloadSecureFile@1
        name: WorkflowTriggerKey
        displayName: 'Download workflow trigger key'
        inputs:
          secureFile: '${{ parameters.authGithubWorkflow }}'
      - bash: |
          set -e
          KEY="$(cat $(WorkflowTriggerKey.secureFilePath) | base64 -w0)"
          echo "##vso[task.setvariable variable=value;isoutput=true]$KEY"
        name: key
