version: "3.8"
services:

  client-envoy:
    build:
      context: .
      dockerfile: Dockerfile-client
    depends_on:
      backend-local-1:
        condition: service_healthy
      backend-local-2:
        condition: service_healthy
      backend-remote-1:
        condition: service_healthy
      backend-remote-2:
        condition: service_healthy

  backend-local-1:
    build:
      context: ../shared/python
      target: aiohttp-service
    volumes:
    - ./service.py:/code/service.py
    environment:
    - HOST=backend-local-1

  backend-local-2:
    build:
      context: ../shared/python
      target: aiohttp-service
    volumes:
    - ./service.py:/code/service.py
    environment:
    - HOST=backend-local-2

  backend-remote-1:
    build:
      context: ../shared/python
      target: aiohttp-service
    volumes:
    - ./service.py:/code/service.py
    environment:
    - HOST=backend-remote-1

  backend-remote-2:
    build:
      context: ../shared/python
      target: aiohttp-service
    volumes:
    - ./service.py:/code/service.py
    environment:
    - HOST=backend-remote-2
