inputs:
  target:
    required: true
    type: string
  rbe:
    type: boolean
    default: true
  managed:
    type: boolean
    default: true

  auth_bazel_rbe:
    type: string
    default: ''

  bazel_extra:
    type: string
    default:
  bazel_rbe_jobs:
    type: number
    default: 75

  command_prefix:
    type: string
    default: ./ci/run_envoy_docker.sh
  command_ci:
    type: string
    default: ./ci/do_ci.sh
  catch-errors:
    type: boolean
    default: false
  error-match:
    type: string
    default: |
      ERROR
  warning-match:
    type: string
    default: |
      WARNING
  notice-match:
    type: string
    default: |
      NOTICE

  env:
    type: string

  GITHUB_TOKEN:
    required: true

runs:
  using: composite
  steps:
  - uses: envoyproxy/toolshed/gh-actions/github/run@actions-v0.0.35
    name: 'Run CI target ${{ inputs.target }}'
    with:
      catch-errors: ${{ inputs.catch-errors }}
      container-command: ${{ inputs.command_prefix }}
      command-prefix: ${{ inputs.command_ci }}
      command: ${{ inputs.target }}
      env: ${{ inputs.env }}
      error-match: ${{ inputs.error-match }}
      notice-match: ${{ inputs.notice-match }}
      warning-match: ${{ inputs.warning-match }}
    env:
      GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      ENVOY_DOCKER_BUILD_DIR: ${{ runner.temp }}
      ENVOY_RBE: ${{ inputs.rbe != 'false' && 1 || '' }}
      GCP_SERVICE_ACCOUNT_KEY: ${{ inputs.rbe && inputs.auth_bazel_rbe || '' }}
      BAZEL_BUILD_EXTRA_OPTIONS: >-
        --config=remote-ci
        ${{ inputs.bazel_extra }}
        ${{ inputs.rbe != 'false' && format('--jobs={0}', inputs.bazel_rbe_jobs) || '' }}
      BAZEL_FAKE_SCM_REVISION: ${{ github.event_name == 'pull_request' && 'e3b4a6e9570da15ac1caffdded17a8bebdc7dfc9' || '' }}
      CI_TARGET_BRANCH: ${{ github.event_name == 'pull_request' && github.event.base.ref || github.ref }}
