version: "3.8"
services:

  front-envoy:
    build:
      context: .
      dockerfile: Dockerfile-frontenvoy
    depends_on:
      frontend-service:
        condition: service_healthy
    ports:
    - "${PORT_PROXY:-8000}:10000"

  frontend-service:
    build:
      context: ../../shared/python
      target: aiohttp-service
    volumes:
    - ./service.py:/code/service.py
    - ./index.html:/code/index.html
