version: "3.8"
services:

  # front-proxy
  front-envoy:
    build:
      context: .
      dockerfile: Dockerfile-frontenvoy
    depends_on:
      service1:
        condition: service_healthy
      service2:
        condition: service_healthy
    ports:
    - "${PORT_PROXY:-8080}:8080"
    - "${PORT_HTTPS:-8443}:8443"
    - "${PORT_STATS:-8001}:8001"

  service1:
    build:
      context: ../shared/flask
      target: tracing-flask
    volumes:
    - ./service-envoy.yaml:/etc/service-envoy.yaml
    environment:
    - SERVICE_NAME=1

  service2:
    build:
      context: ../shared/flask
      target: tracing-flask
    volumes:
    - ./service-envoy.yaml:/etc/service-envoy.yaml
    environment:
    - SERVICE_NAME=2
