version: "3.8"
services:

  envoy-stats:
    build:
      context: .
      dockerfile: Dockerfile-gzip
    depends_on:
      service:
        condition: service_healthy
    ports:
    - "${PORT_PROXY:-10000}:10000"
    - "${PORT_STATS0:-9901}:9901"
    - "${PORT_STATS1:-9902}:9902"

  service:
    build:
      context: ../shared/flask
      target: data-flask
    volumes:
    - ./service.py:/code/service.py
