version: "3.8"
services:

  proxy:
    build:
      context: .
      dockerfile: Dockerfile-proxy
    depends_on:
      helloworld_service:
        condition: service_healthy
    ports:
    - "${PORT_PROXY:-10000}:10000"

  helloworld_service:
    build:
      context: ../shared/flask
    volumes:
    - ./service.py:/code/service.py
