version: "3.8"

services:

  # Requires the build of the stubs first
  grpc-server:
    build:
      context: server
      dockerfile: ../../shared/golang/Dockerfile
      target: golang-grpc-server

  grpc-server-proxy:
    build:
      context: .
      dockerfile: Dockerfile-server

  # Requires the build of the stubs first
  grpc-client:
    build:
      context: client
      dockerfile: ../../shared/python/Dockerfile
      target: python-grpc-client
    environment:
      CLIENT_PROXY: http://grpc-client-proxy:9911
      PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: python

  grpc-client-proxy:
    build:
      context: .
      dockerfile: Dockerfile-client
