version: '3.8'
services:

  envoy:
    build:
      context: .
      dockerfile: Dockerfile-envoy
    ports:
    - "${PORT_PROXY0:-80}-${PORT_PROXY1:-81}:80"
    - "${PORT_ADMIN:-8081}:8081"
    depends_on:
      http_service:
        condition: service_healthy
      lrs_server:
        condition: service_started

  http_service:
    build:
      context: ../shared/flask
    volumes:
    - ./service.py:/code/service.py

  lrs_server:
    build:
      context: .
      dockerfile: Dockerfile-lrs
    volumes:
    - /go/src/github.com/envoyproxy/envoy/examples/load-reporting-service
