version: '3.8'
services:

  flask_service:
    build:
      context: ../shared/flask
    image: flask_service:python-3.10-slim-bullseye
    restart: "no"
    deploy:
      replicas: 0

  envoy:
    build:
      context: .
      dockerfile: Dockerfile-envoy
    ports:
    - "${PORT_PROXY0:-80}-${PORT_PROXY0:-81}:80"
    - "${PORT_ADMIN:-8081}:8081"
    depends_on:
      http_service:
        condition: service_healthy
      lrs_server:
        condition: service_started

  http_service:
    build:
      context: ../shared/service
    volumes:
    - ./service.py:/code/service.py

  lrs_server:
    build:
      context: .
      dockerfile: Dockerfile-lrs
    volumes:
    - /go/src/github.com/envoyproxy/envoy/examples/load-reporting-service
