trigger:
  branches:
    include:
    - "main"
    - "release/v*"
  tags:
    include:
    - "v*"


# PR build config is manually overridden in Azure pipelines UI with different secrets
pr: none


variables:
- name: isDev
  # This must be checked/set in a `step` from the VERSION.txt file, in order to be useful
  value: true
- name: isMain
  value: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
- name: isReleaseBranch
  value: $[startsWith(variables['Build.SourceBranch'], 'refs/heads/release/v')]
- name: isTaggedRelease
  value: $[startsWith(variables['Build.SourceBranch'], 'refs/tags/v')]
- name: isStableBranch
  # A release branch can be either `main` or a `release/v1.x` stable branch
  value: $[or(eq(variables['isMain'], 'true'), eq(variables['isReleaseBranch'], 'true'))]

## Variable settings
# Caches (tip: append a version suffix while testing caches)
- name: buildImageCacheVersion
  value: v0
- name: dockerBuildCacheVersion
  value: v0


stages:
# Presubmit/default
- ${{ if ne(variables['Build.DefinitionName'], 'envoy-postsubmit') }}:
  - template: stages.yml

# Postsubmit
- ${{ if eq(variables['Build.DefinitionName'], 'envoy-postsubmit') }}:
  - template: stages.yml
    parameters:
      buildStageDeps:
      - env
      macBuildStageDeps:
      - env
      windowsBuildStageDeps:
      - env
