version: '3.8'
services:

  front-envoy:
    build:
      context: .
      dockerfile: Dockerfile-frontenvoy
    depends_on:
      service:
        condition: service_healthy
    ports:
    - "${PORT_CROSS:-8002}:10000"

  service:
    build:
      context: ../../shared/flask
    volumes:
    - ./service.py:/code/service.py
    - ../index.html:/code/index.html
