version: '3.8'
services:

  flask_service:
    build:
      context: ../../shared/flask
    image: flask_service:python-3.10-slim-bullseye
    restart: "no"
    deploy:
      replicas: 0

  front-envoy:
    build:
      context: .
      dockerfile: Dockerfile-frontenvoy
    depends_on:
      service:
        condition: service_healthy
    ports:
    - "${PORT_CROSS:-8002}:10000"

  service:
    build:
      context: ../../shared/service
    volumes:
    - ./service.py:/code/service.py
    - ../index.html:/code/index.html
