name: Environment

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      # Authoritative configuration for build image/s
      build_image_repo:
        type: string
        default: envoyproxy/envoy-build-ubuntu
      build_image_sha:
        type: string
        default: 8781bc7e431b754c142edbfc937905fdf343db91f3fe19bbf54c362828db9849
      build_image_mobile_sha:
        type: string
        default: 292273a428ebb093cc69c2f225c7c4218ff2ea84e0cb6ee80e7a6771a09e026f
      # this is authoritative, but is not currently used in github ci
      build_image_gcr_sha:
        type: string
        default: af98298b715958527d3c3b42ae968a09223d237c843e129c586b7e76b8c69a0d
      build_image_tag:
        type: string
        default: 7467652575122d8d54e767a68f141598bd855383

      check-mobile-run:
        type: boolean
        default: true
      prime-build-image:
        type: boolean
        default: false
      repo-ref:
        type: string
        default:
      repo-ref-name:
        type: string
        default:
      repo-ref-sha:
        type: string
        default:

    outputs:
      debug:
        value: false
      agent_ubuntu:
        value: ubuntu-22.04
      build_image_ubuntu:
        value: ${{ jobs.repo.outputs.build_image_ubuntu }}
      build_image_ubuntu_mobile:
        value: ${{ jobs.repo.outputs.build_image_ubuntu_mobile }}
      mobile_android_build:
        value: ${{ jobs.repo.outputs.mobile_android_build }}
      mobile_android_build_all:
        value: ${{ jobs.repo.outputs.mobile_android_build_all }}
      mobile_android_tests:
        value: ${{ jobs.repo.outputs.mobile_android_tests }}
      mobile_asan:
        value: ${{ jobs.repo.outputs.mobile_asan }}
      mobile_cc_tests:
        value: ${{ jobs.repo.outputs.mobile_cc_tests }}
      mobile_compile_time_options:
        value: ${{ jobs.repo.outputs.mobile_compile_time_options }}
      mobile_coverage:
        value: ${{ jobs.repo.outputs.mobile_coverage }}
      mobile_formatting:
        value: ${{ jobs.repo.outputs.mobile_formatting }}
      mobile_ios_build:
        value: ${{ jobs.repo.outputs.mobile_ios_build }}
      mobile_ios_build_all:
        value: ${{ jobs.repo.outputs.mobile_ios_build_all }}
      mobile_ios_tests:
        value: ${{ jobs.repo.outputs.mobile_ios_tests }}
      mobile_release_validation:
        value: ${{ jobs.repo.outputs.mobile_release_validation }}
      mobile_tsan:
        value: ${{ jobs.repo.outputs.mobile_tsan }}
      repo-ref:
        value: ${{ jobs.repo.outputs.repo-ref }}
      repo-ref-name:
        value: ${{ jobs.repo.outputs.repo-ref-name }}
      repo-ref-sha:
        value: ${{ jobs.repo.outputs.repo-ref-sha }}
      repo-ref-sha-short:
        value: ${{ jobs.repo.outputs.repo-ref-sha-short }}
      repo-ref-title:
        value: ${{ jobs.repo.outputs.repo-ref-title }}
      trusted:
        value: ${{ jobs.repo.outputs.trusted }}
      version-dev:
        value: ${{ jobs.repo.outputs.version-dev }}
      version-patch:
        value: ${{ jobs.repo.outputs.version-patch }}

concurrency:
  group: |
    ${{ github.actor != 'trigger-release-envoy[bot]'
        && github.event.inputs.head_ref
        || github.run_id
    }}-${{ github.workflow }}-env
  cancel-in-progress: true

jobs:
  repo:
    if: ${{ github.repository == 'envoyproxy/envoy' || vars.ENVOY_CI }}
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      pull-requests: read
    outputs:
      build_image_ubuntu: ${{ steps.env.outputs.build_image_ubuntu }}
      build_image_ubuntu_mobile: ${{ steps.env.outputs.build_image_ubuntu_mobile }}
      mobile_android_build: ${{ steps.env.outputs.mobile_android_build }}
      mobile_android_build_all: ${{ steps.env.outputs.mobile_android_build_all }}
      mobile_android_tests: ${{ steps.env.outputs.mobile_android_tests }}
      mobile_asan: ${{ steps.env.outputs.mobile_asan }}
      mobile_cc_tests: ${{ steps.env.outputs.mobile_cc_tests }}
      mobile_compile_time_options: ${{ steps.env.outputs.mobile_compile_time_options }}
      mobile_coverage: ${{ steps.env.outputs.mobile_coverage }}
      mobile_formatting: ${{ steps.env.outputs.mobile_formatting }}
      mobile_ios_build: ${{ steps.env.outputs.mobile_ios_build }}
      mobile_ios_build_all: ${{ steps.env.outputs.mobile_ios_build_all }}
      mobile_ios_tests: ${{ steps.env.outputs.mobile_ios_tests }}
      mobile_release_validation: ${{ steps.env.outputs.mobile_release_validation }}
      mobile_tsan: ${{ steps.env.outputs.mobile_tsan }}
      repo-ref: ${{ steps.ref.outputs.value }}
      repo-ref-name: ${{ steps.env.outputs.repo-ref-name }}
      repo-ref-sha: ${{ steps.env.outputs.repo-ref-sha }}
      repo-ref-sha_short: ${{ steps.env.outputs.repo-ref-sha-short }}
      repo-ref-title: ${{ steps.env.outputs.repo-ref-title }}
      trusted: ${{ steps.env.outputs.trusted }}
      version-dev: ${{ steps.env.outputs.version-dev }}
      version-patch: ${{ steps.env.outputs.version-patch }}
    steps:
    - uses: actions/checkout@v4
      name: Checkout Envoy repository
      with:
        fetch-depth: ${{ ! (inputs.check-mobile-run || ! startsWith(github.event_name, 'pull_request')) && 1 || 0 }}
        # WARNING: This allows untrusted code to run!!!
        #  If this is set, then anything before or after in the job should be regarded as
        #  compromised.
        ref: ${{ startsWith(github.event_name, 'pull_request') && inputs.repo-ref || '' }}

    - uses: ./.github/actions/env
      name: Generate environment variables
      id: env
      with:
        check-mobile-run: ${{ inputs.check-mobile-run }}
        repo-ref: ${{ inputs.repo-ref }}
        repo-ref-name: ${{ inputs.repo-ref-name }}
        repo-ref-sha: ${{ inputs.repo-ref-sha }}
        build_image_repo: ${{ inputs.build_image_repo }}
        build_image_tag: ${{ inputs.build_image_tag }}
        build_image_mobile_sha: ${{ inputs.build_image_mobile_sha }}
        build_image_sha: ${{ inputs.build_image_sha }}
    - uses: envoyproxy/toolshed/gh-actions/github/merge-commit@actions-v0.1.7
      id: merge-commit
      if: ${{ github.event_name == 'pull_request_target' }}
      with:
        repository: ${{ github.repository }}
        pr: ${{ github.event.number }}
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: 'Set ref'
      id: ref
      run: |
        echo "value=${{ steps.merge-commit.outputs.sha || steps.env.outputs.repo_ref }}" >> $GITHUB_OUTPUT

    - name: 'Print env'
      run: |
        echo "version-dev=${{ steps.env.outputs.version-dev }}"
        echo "version-patch=${{ steps.env.outputs.version-patch }}"
        echo "trusted=${{ steps.env.outputs.trusted }}"
        echo "repo-ref=${{ steps.ref.outputs.value }}"
        echo "repo-ref-name=${{ steps.env.outputs.repo-ref-name }}"
        echo "repo-ref-pr-number=${{ steps.env.outputs.repo-ref-pr-number }}"
        echo "repo-ref-sha=${{ steps.env.outputs.repo-ref-sha }}"
        echo "repo-ref-sha-short=${{ steps.env.outputs.repo-ref-sha-short }}"
        echo "repo-ref-title=${{ steps.env.outputs.repo-ref-title }}"
        echo "build_image_ubuntu=${{ steps.env.outputs.build_image_ubuntu }}"
        echo "build_image_ubuntu_mobile=${{ steps.env.outputs.build_image_ubuntu_mobile }}"
        echo
        if [[ -n "${{ steps.env.outputs.repo-ref-pr-number }}" ]]; then
            echo "PR: https://github.com/${{ github.repository }}/pull/${{ steps.env.outputs.repo-ref-pr-number }}"
        fi

  cache:
    if: ${{ inputs.prime-build-image }}
    uses: ./.github/workflows/_cache_docker.yml
    with:
      image_repo: ${{ inputs.build_image_repo }}
      image_tag: ${{ inputs.build_image_tag }}
      image_sha: ${{ inputs.build_image_sha }}
