name: Environment

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      check_mobile_run:
        type: boolean
        default: true
      prime_build_image:
        type: boolean
        default: false

      start_check_status:
        type: string
        default:

    outputs:
      agent_ubuntu:
        value: ubuntu-22.04
      build_image_ubuntu:
        value: ${{ jobs.repo.outputs.build_image_ubuntu }}
      build_image_ubuntu_mobile:
        value: ${{ jobs.repo.outputs.build_image_ubuntu_mobile }}
      mobile_android_build:
        value: ${{ jobs.repo.outputs.mobile_android_build }}
      mobile_android_build_all:
        value: ${{ jobs.repo.outputs.mobile_android_build_all }}
      mobile_android_tests:
        value: ${{ jobs.repo.outputs.mobile_android_tests }}
      mobile_asan:
        value: ${{ jobs.repo.outputs.mobile_asan }}
      mobile_cc_tests:
        value: ${{ jobs.repo.outputs.mobile_cc_tests }}
      mobile_compile_time_options:
        value: ${{ jobs.repo.outputs.mobile_compile_time_options }}
      mobile_coverage:
        value: ${{ jobs.repo.outputs.mobile_coverage }}
      mobile_formatting:
        value: ${{ jobs.repo.outputs.mobile_formatting }}
      mobile_ios_build:
        value: ${{ jobs.repo.outputs.mobile_ios_build }}
      mobile_ios_build_all:
        value: ${{ jobs.repo.outputs.mobile_ios_build_all }}
      mobile_ios_tests:
        value: ${{ jobs.repo.outputs.mobile_ios_tests }}
      mobile_release_validation:
        value: ${{ jobs.repo.outputs.mobile_release_validation }}
      mobile_tsan:
        value: ${{ jobs.repo.outputs.mobile_tsan }}

      trusted:
        value: ${{ jobs.repo.outputs.trusted }}

      version_dev:
        value: ${{ jobs.repo.outputs.version_dev }}
      version_patch:
        value: ${{ jobs.repo.outputs.version_patch }}

concurrency:
  group: ${{ github.head_ref || github.run_id }}-${{ github.workflow }}-env
  cancel-in-progress: true

jobs:
  repo:
    if: github.repository == 'envoyproxy/envoy'
    runs-on: ubuntu-22.04
    outputs:
      build_image_ubuntu: ${{ steps.env.outputs.build_image_ubuntu }}
      build_image_ubuntu_mobile: ${{ steps.env.outputs.build_image_ubuntu_mobile }}
      mobile_android_build: ${{ steps.env.outputs.mobile_android_build }}
      mobile_android_build_all: ${{ steps.env.outputs.mobile_android_build_all }}
      mobile_android_tests: ${{ steps.env.outputs.mobile_android_tests }}
      mobile_asan: ${{ steps.env.outputs.mobile_asan }}
      mobile_cc_tests: ${{ steps.env.outputs.mobile_cc_tests }}
      mobile_compile_time_options: ${{ steps.env.outputs.mobile_compile_time_options }}
      mobile_coverage: ${{ steps.env.outputs.mobile_coverage }}
      mobile_formatting: ${{ steps.env.outputs.mobile_formatting }}
      mobile_ios_build: ${{ steps.env.outputs.mobile_ios_build }}
      mobile_ios_build_all: ${{ steps.env.outputs.mobile_ios_build_all }}
      mobile_ios_tests: ${{ steps.env.outputs.mobile_ios_tests }}
      mobile_release_validation: ${{ steps.env.outputs.mobile_release_validation }}
      mobile_tsan: ${{ steps.env.outputs.mobile_tsan }}
      trusted: ${{ steps.env.outputs.trusted }}
      version_dev: ${{ steps.env.outputs.version_dev }}
      version_patch: ${{ steps.env.outputs.version_patch }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: ${{ ! inputs.check_mobile_run && 1 || 0 }}
    - uses: ./.github/actions/env
      id: env
      with:
        check_mobile_run: ${{ inputs.check_mobile_run }}

    - name: 'Print env'
      run: |
        echo "version_dev=${{ steps.env.outputs.version_dev }}"
        echo "version_patch=${{ steps.env.outputs.version_patch }}"
        echo "build_image_ubuntu=${{ steps.env.outputs.build_image_ubuntu }}"
        echo "build_image_ubuntu_mobile=${{ steps.env.outputs.build_image_ubuntu_mobile }}"
        echo "trusted=${{ steps.env.outputs.trusted }}"

  cache:
    if: ${{ inputs.prime_build_image }}
    # This uses a separate job to ensure correct concurrency
    uses: ./.github/workflows/_cache_docker.yml

  check:
    if: ${{ inputs.start_check_status && github.event_name != 'pull_request' }}
    uses: ./.github/workflows/_workflow-start.yml
    permissions:
      contents: read
      statuses: write
    with:
      workflow_name: ${{ inputs.start_check_status }}
