name: Publish

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      build-image-ubuntu:
        type: string
        default: ''
      dependency-review:
        type: boolean
        default: false
      repo-ref:
        type: string

concurrency:
  group: ${{ github.head_ref || github.run_id }}-${{ github.workflow }}-publish
  cancel-in-progress: true

jobs:
  prechecks:
    strategy:
      matrix:
        include:
        - target: deps
          rbe: false
    uses: ./.github/workflows/_ci.yml
    name: ${{ matrix.target }}
    permissions:
      contents: read
      packages: read
    with:
      target: ${{ matrix.target }}
      rbe: ${{ matrix.rbe }}
      bazel-extra: '--config=rbe-envoy-engflow'
      cache-build-image: ${{ inputs.build-image-ubuntu }}
      repo-ref: ${{ inputs.repo-ref }}
      catch-errors: true
      error-match: |
        ERROR
        ClientConnectorError

  dependency-review:
    runs-on: ubuntu-22.04
    if: ${{ inputs.dependency-review }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.repo-ref }}
        persist-credentials: false
    - name: Dependency Review
      uses: actions/dependency-review-action@6c5ccdad469c9f8a2996bfecaec55a631a347034
