name: Publish

permissions:
  contents: read

# The matrices in this config can be combined once the calling workflow has shifted
# to a `pull_request`/`commit` pattern (ie not `workflow_dispatch`)
#
# For now pre/post submit is split between `publish_ci`/`publish`, the latter running
# only for "trusted" runs and having access to secrets/permissions

on:
  workflow_call:
    inputs:
      trusted:
        type: boolean
        default: false
      build_image_ubuntu:
        type: string
        default: ''
      version_dev:
        type: string
        default: ''
      head_ref:
        type: string
        default: ''
      repo_ref:
        type: string
      given_ref:
        type: string

concurrency:
  group: ${{ github.head_ref || github.run_id }}-${{ github.workflow }}-publish
  cancel-in-progress: true

jobs:
  publish_ci:
    if: ${{ ! inputs.trusted }}
    name: ${{ matrix.name || matrix.target }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - target: publish
          name: github
          run_pre: ./.github/actions/publish/release/setup
          run_pre_with: |
            ref: ${{ inputs.given_ref }}
            bucket: envoy-pr
          env: |
            export ENVOY_PUBLISH_DRY_RUN=1
    uses: ./.github/workflows/_ci.yml
    with:
      target: ${{ matrix.target }}
      rbe: false
      managed: true
      cache_build_image: ${{ inputs.build_image_ubuntu }}
      run_pre: ${{ matrix.run_pre }}
      run_pre_with: ${{ matrix.run_pre_with }}
      env: ${{ matrix.env }}
      trusted: false
      repo_ref: ${{ inputs.repo_ref }}

  publish:
    if: ${{ inputs.trusted }}
    name: ${{ matrix.name || matrix.target }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
        - target: publish
          name: github
          run_pre: ./.github/actions/publish/release/setup
          run_pre_with: |
            ref: ${{ inputs.given_ref }}
            bucket: envoy-postsubmit
          env: |
            if [[ '${{ inputs.version_dev }}' != '' ]]; then
                export ENVOY_PUBLISH_DRY_RUN=1
            fi
    uses: ./.github/workflows/_ci.yml
    with:
      target: ${{ matrix.target }}
      rbe: false
      managed: true
      cache_build_image: ${{ inputs.build_image_ubuntu }}
      run_pre: ${{ matrix.run_pre }}
      run_pre_with: ${{ matrix.run_pre_with }}
      env: ${{ matrix.env }}
      trusted: true
