name: mobile_cc_tests

on:
  push:
    branches:
    - main
  pull_request:

concurrency:
  group: ${{ github.head_ref-github.workflow || github.run_id }}
  cancel-in-progress: true

jobs:
  cctests:
    if: github.repository == 'envoyproxy/envoy'
    name: cc_tests
    runs-on: ubuntu-20.04
    timeout-minutes: 120
    container:
      image: envoyproxy/envoy-build-ubuntu:7304f974de2724617b7492ccb4c9c58cd420353a
    steps:
    - uses: actions/checkout@v3
    - name: Add safe directory
      run: git config --global --add safe.directory /__w/envoy/envoy
    - env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: 'Run tests'
        # Regression test using the new API listener. TODO(#2711) clean up.
      run: |
        cd mobile && ./bazelw test \
            --action_env=LD_LIBRARY_PATH \
            --test_output=all \
            --copt=-DUSE_API_LISTENER \
            $([ -z $GITHUB_TOKEN ] || echo "--config=remote-ci-linux") \
            --remote_header="Authorization=Bearer $GITHUB_TOKEN" \
            //test/cc/...
