name: commands
on:
  issue_comment:
    types: [created]

jobs:
  retest:
    if: |
      ${{
         github.event.issue.pull_request
         && github.repository == 'envoyproxy/envoy'
         && github.actor != 'repokitteh-read-only[bot]'
         && github.actor != 'dependabot[bot]'
      }}
    name: Retest
    runs-on: ubuntu-latest
    steps:
    - uses: jpsim/retest@c158dec0a7f67cb85f8367468dc8a9a75308bb7f
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
