name: commands

on:
  issue_comment:
    types:
    - created

permissions:
  contents: read

jobs:
  retest:
    if: >-
      ${{
         github.event.issue.pull_request
         && github.repository == 'envoyproxy/envoy'
         && github.actor != 'repokitteh-read-only[bot]'
         && github.actor != 'dependabot[bot]'
      }}
    name: Retest
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: write
      actions: write
      checks: read
    steps:
    - uses: envoyproxy/toolshed/gh-actions/retest@actions-v0.1.7
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        azp_org: cncf
        azp_token: ${{ secrets.AZP_TOKEN }}
