name: Publish & verify

on:
  # This runs untrusted code, do not expose secrets in the verify job
  workflow_dispatch:
    inputs:
      ref:
        description: "Git SHA ref to checkout"
      sha:
        description: "Git SHA of commit HEAD (ie last commit of PR)"
      head_ref:
        description: "Ref for grouping PRs"

concurrency:
  group: ${{ github.event.inputs.head_ref || github.run_id }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  check:
    if: |
      ${{
          github.repository == 'envoyproxy/envoy'
          && (!contains(github.actor, '[bot]')
              || github.actor == 'trigger-workflow-envoy[bot]')
      }}
    uses: ./.github/workflows/_workflow-start.yml
    permissions:
      contents: read
      statuses: write
    with:
      workflowName: Verify/examples

  env:
    uses: ./.github/workflows/_env.yml
  cache:
    needs:
    - env
    uses: ./.github/workflows/_cache_docker.yml
    with:
      image_tag: "${{ needs.env.outputs.build_image_ubuntu }}"

  ci:
    needs:
    - check
    - env
    - cache
    strategy:
      fail-fast: false
      matrix:
        include:
        - target: verify_examples
          rbe: false
          managed: true
          cache_build_image: ""
          command_prefix: ""
          diskspace_hack: true
          run_pre: ./.github/actions/verify/examples/setup
          run_pre_with: |
            ref: ${{ inputs.ref }}
          env: |
            export NO_BUILD_SETUP=1
    uses: ./.github/workflows/_ci.yml
    name: CI ${{ matrix.target }}
    with:
      target: ${{ matrix.target }}
      rbe: ${{ matrix.rbe }}
      managed: ${{ matrix.managed }}
      cache_build_image: ${{ matrix.cache_build_image }}
      diskspace_hack: ${{ matrix.diskspace_hack }}
      command_prefix: ${{ matrix.command_prefix }}
      run_pre: ${{ matrix.run_pre }}
      run_pre_with: ${{ matrix.run_pre_with }}
      env: ${{ matrix.env }}
    secrets: inherit
