name: 'Sync downstream'

on:
  push:
    branches:
    - main

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  sync:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        downstream:
        - go-control-plane
        - envoy-filter-example
        - data-plane-api
    steps:
    - uses: envoyproxy/toolshed/gh-actions/dispatch@1f1feae1e372dde41ecc6830028989bb6037c480
      with:
        repository: "envoyproxy/${{ matrix.downstream }}"
        ref: main
        key: "${{ secrets.ENVOY_CI_SYNC_APP_KEY }}"
        workflow: envoy-sync.yaml
        app_id: ${{ secrets.ENVOY_CI_SYNC_APP_ID }}
