name: Publish & verify

on:
  # This runs untrusted code, do not expose secrets in the verify job
  workflow_dispatch:
    inputs:
      ref:
        description: "Git SHA ref to checkout"
      sha:
        description: "Git SHA of commit HEAD (ie last commit of PR)"
      head_ref:
        description: "Ref for grouping PRs"

concurrency:
  group: ${{ github.event.inputs.head_ref || github.run_id }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  env:
    if: |
      ${{
          github.repository == 'envoyproxy/envoy'
          && (!contains(github.actor, '[bot]')
              || github.actor == 'trigger-workflow-envoy[bot]'
              || github.actor == 'trigger-release-envoy[bot]')
      }}
    uses: ./.github/workflows/_env.yml
    with:
      check_mobile_run: false
      prime_build_image: true
      start_check_status: Verify/examples
      repo_ref_sha: ${{ inputs.ref_sha }}
      repo_ref_name: ${{ inputs.head_ref }}

    permissions:
      contents: read
      statuses: write

  verify:
    uses: ./.github/workflows/_stage_verify.yml
    name: Verify (${{ inputs.trusted && 'postsubmit' || 'pr' }}:${{ needs.env.outputs.repo_ref_name }}@${{ needs.env.outputs.repo_ref_sha_short }})
    needs:
    - env
    with:
      trusted: ${{ needs.env.outputs.trusted && true || false }}
      repo_ref: ${{ needs.env.outputs.trusted == 'false' && inputs.ref || '' }}
