name: 'Sync downstream'

permissions:
  contents: read

on:
  push:
    branches:
    - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  sync:
    runs-on: ubuntu-22.04
    if: >-
      ${{
          github.repository == 'envoyproxy/envoy'
          && (github.event.push
              || !contains(github.actor, '[bot]'))
      }}
    strategy:
      fail-fast: false
      matrix:
        downstream:
        - go-control-plane
        - envoy-filter-example
        - data-plane-api
        - mobile-website
    steps:
    - uses: envoyproxy/toolshed/gh-actions/appauth@6b3ddd1e42c252d68fb98973760c0ee1943c9c21  # actions-v0.2.20
      id: appauth
      with:
        app_id: ${{ secrets.ENVOY_CI_SYNC_APP_ID }}
        key: ${{ secrets.ENVOY_CI_SYNC_APP_KEY }}
    - uses: envoyproxy/toolshed/gh-actions/dispatch@6b3ddd1e42c252d68fb98973760c0ee1943c9c21  # actions-v0.2.20
      with:
        repository: "envoyproxy/${{ matrix.downstream }}"
        ref: main
        token: ${{ steps.appauth.outputs.token }}
        workflow: envoy-sync.yaml
