name: Publish & verify

permissions:
  contents: read

on:
  # This runs untrusted code, do not expose secrets in the verify job
  workflow_dispatch:
    inputs:
      ref:
        description: "Git SHA ref to checkout"
      sha:
        description: "Git SHA of commit HEAD (ie last commit of PR)"
      head_ref:
        description: "Ref for grouping PRs"

concurrency:
  group: |
    ${{ github.actor != 'trigger-release-envoy[bot]'
        && github.event.inputs.head_ref
        || github.run_id
    }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  env:
    if: >-
      ${{
          github.repository == 'envoyproxy/envoy'
          && (!contains(github.actor, '[bot]')
              || github.actor == 'trigger-workflow-envoy[bot]'
              || github.actor == 'trigger-release-envoy[bot]')
      }}
    uses: ./.github/workflows/_env.yml
    with:
      check_mobile_run: false
      prime_build_image: true
      start_check_status: Verify/examples
      repo_ref: ${{ inputs.ref }}
      repo_ref_sha: ${{ inputs.sha }}
      repo_ref_name: ${{ inputs.head_ref }}

    permissions:
      contents: read
      statuses: write

  publish:
    needs:
    - env
    uses: ./.github/workflows/_stage_publish.yml
    name: Publish ${{ needs.env.outputs.repo_ref_title }}
    with:
      build_image_ubuntu: ${{ needs.env.outputs.build_image_ubuntu }}
      trusted: ${{ needs.env.outputs.trusted == 'true' && true || false }}
      version_dev: ${{ needs.env.outputs.version_dev }}
      given_ref: ${{ inputs.ref }}
      repo_ref: ${{ needs.env.outputs.trusted != 'true' && inputs.ref || '' }}
    permissions:
      contents: write

  verify:
    uses: ./.github/workflows/_stage_verify.yml
    name: Verify ${{ needs.env.outputs.repo_ref_title }}
    needs:
    - env
    with:
      trusted: ${{ needs.env.outputs.trusted == 'true' && true || false }}
      given_ref: ${{ inputs.ref }}
      repo_ref: ${{ needs.env.outputs.trusted != 'true' && needs.env.outputs.repo_ref || '' }}
