name: Publish & verify

permissions:
  contents: read

on:
  # This runs untrusted code, do not expose secrets in the verify job
  workflow_dispatch:
    inputs:
      ref:
        description: "Git SHA ref to checkout"
      sha:
        description: "Git SHA of commit HEAD (ie last commit of PR)"
      head_ref:
        description: "Ref for grouping PRs"

concurrency:
  group: |
    ${{ github.actor != 'trigger-release-envoy[bot]'
        && github.event.inputs.head_ref
        || github.run_id
    }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  env:
    if: >-
      ${{
          (github.repository == 'envoyproxy/envoy'
           || vars.ENVOY_CI)
          && (!contains(github.actor, '[bot]')
              || github.actor == 'trigger-workflow-envoy[bot]'
              || github.actor == 'trigger-release-envoy[bot]')
      }}
    uses: ./.github/workflows/_env.yml
    with:
      check-mobile-run: false
      prime-build-image: true
      repo-ref: ${{ inputs.ref }}
      repo-ref-sha: ${{ inputs.sha }}
      repo-ref-name: ${{ inputs.head_ref }}
    permissions:
      contents: read
      packages: read
      pull-requests: read

  check:
    if: ${{ github.event_name != 'pull_request' }}
    uses: ./.github/workflows/_workflow-start.yml
    permissions:
      contents: read
      statuses: write
    with:
      workflow_name: Verify/examples
      sha: ${{ inputs.sha }}

  publish:
    needs:
    - env
    - check
    uses: ./.github/workflows/_stage_publish.yml
    name: Publish ${{ needs.env.outputs.repo-ref-title }}
    with:
      build_image_ubuntu: ${{ needs.env.outputs.build_image_ubuntu }}
      trusted: ${{ needs.env.outputs.trusted == 'true' && true || false }}
      version-dev: ${{ needs.env.outputs.version-dev }}
      repo-ref: ${{ inputs.ref }}
      sha: ${{ inputs.sha }}
    permissions:
      contents: read
      packages: read
    secrets:
      ENVOY_CI_SYNC_APP_ID: ${{ secrets.ENVOY_CI_SYNC_APP_ID }}
      ENVOY_CI_SYNC_APP_KEY: ${{ secrets.ENVOY_CI_SYNC_APP_KEY }}
      ENVOY_CI_PUBLISH_APP_ID: ${{ secrets.ENVOY_CI_PUBLISH_APP_ID }}
      ENVOY_CI_PUBLISH_APP_KEY: ${{ secrets.ENVOY_CI_PUBLISH_APP_KEY }}

  verify:
    uses: ./.github/workflows/_stage_verify.yml
    name: Verify ${{ needs.env.outputs.repo-ref-title }}
    needs:
    - env
    permissions:
      contents: read
    with:
      trusted: ${{ needs.env.outputs.trusted == 'true' && true || false }}
      given_ref: ${{ inputs.ref }}
      repo-ref: ${{ inputs.ref }}
