name: 'Sync downstream'

on:
  push:
    branches:
    - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  sync:
    runs-on: ubuntu-22.04
    if: >-
      ${{
          github.repository == 'envoyproxy/envoy'
          && (github.event.push
              || !contains(github.actor, '[bot]'))
      }}
    strategy:
      fail-fast: false
      matrix:
        downstream:
        - go-control-plane
        - envoy-filter-example
        - data-plane-api
        - mobile-website
    steps:
    - uses: envoyproxy/toolshed/gh-actions/dispatch@actions-v0.1.7
      with:
        repository: "envoyproxy/${{ matrix.downstream }}"
        ref: main
        key: "${{ secrets.ENVOY_CI_SYNC_APP_KEY }}"
        workflow: envoy-sync.yaml
        app_id: ${{ secrets.ENVOY_CI_SYNC_APP_ID }}
