name: Envoy/macos

permissions:
  contents: read

on:
  push:
    branches:
    - main
    - release/v*
  pull_request_target:

concurrency:
  group: ${{ github.event.inputs.head_ref || github.run_id }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  env:
    uses: ./.github/workflows/_env.yml
    with:
      prime_build_image: false
      check_mobile_run: false

  macos:
    needs:
    - env
    strategy:
      fail-fast: false
      matrix:
        include:
        - target: ci/mac_ci_steps.sh
          name: macOS
    uses: ./.github/workflows/_ci.yml
    name: CI ${{ matrix.name || matrix.target }}
    secrets:
      rbe-key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
    with:
      target: ${{ matrix.target }}
      runs-on: macos-12-xl
      command_ci:
      command_prefix:
      repo_ref: ${{ github.event.pull_request.merge_commit_sha }}
      run-du: false
      env: |
        ./ci/mac_ci_setup.sh
        GCP_SERVICE_ACCOUNT_KEY_PATH=$(mktemp -t gcp_service_account.XXXXXX.json)
        bash -c "echo \"${RBE_KEY}\" | base64 --decode > \"${GCP_SERVICE_ACCOUNT_KEY_PATH}\""
        _BAZEL_BUILD_EXTRA_OPTIONS=(
          --remote_download_toplevel
          --flaky_test_attempts=2
          --config=cache-google
          --config=ci
          --google_credentials=${GCP_SERVICE_ACCOUNT_KEY_PATH})
        export BAZEL_BUILD_EXTRA_OPTIONS=${_BAZEL_BUILD_EXTRA_OPTIONS[*]}
