name: ios_tests

on:
  push:
    branches:
    - main
  pull_request:

concurrency:
  group: ${{ github.head_ref-github.workflow || github.run_id }}
  cancel-in-progress: true

jobs:
  swifttests:
    if: github.repository == 'envoyproxy/envoy'
    name: swift_tests
    runs-on: macos-12
    timeout-minutes: 120
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - id: should_run
      name: 'Check whether to run'
      run: ./mobile/tools/should_run_ci.sh
    - name: 'Install dependencies'
      if: steps.should_run.outputs.run_ci_job == 'true'
      run: cd mobile && ./ci/mac_ci_setup.sh
    - name: 'Run swift library tests'
      if: steps.should_run.outputs.run_ci_job == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # runs with admin enabled due to regression testing admin interface
      # runs with the listener enabled due to IdleTimeoutTest not setting up a test backend.
      run: |
        cd mobile && ./bazelw test \
            --experimental_ui_max_stdouterr_bytes=10485760 \
            --test_output=all \
            --config=ios \
            --define envoy_mobile_listener=enabled \
            --build_tests_only \
            $([ -z $GITHUB_TOKEN ] || echo "--config=remote-ci-macos") \
            --define=admin_functionality=enabled \
            //test/swift/...
  objctests:
    if: github.repository == 'envoyproxy/envoy'
    name: c_and_objc_tests
    runs-on: macos-12
    timeout-minutes: 120
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - id: should_run
      name: 'Check whether to run'
      run: ./mobile/tools/should_run_ci.sh
    - name: 'Install dependencies'
      if: steps.should_run.outputs.run_ci_job == 'true'
      run: cd mobile && ./ci/mac_ci_setup.sh
    - name: 'Run Objective-C library tests'
      if: steps.should_run.outputs.run_ci_job == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd mobile && ./bazelw test \
            --test_output=all \
            --config=ios \
            --build_tests_only \
            $([ -z $GITHUB_TOKEN ] || echo "--config=remote-ci-macos") \
            //test/objective-c/...  \
            //test/cc/unit:envoy_config_test
