name: mobile_core

on:
  push:
    branches:
    - main
  pull_request:

concurrency:
  group: ${{ github.head_ref || github.run_id }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  env:
    if: ${{ github.repository == 'envoyproxy/envoy' }}
    uses: ./.github/workflows/env.yml
    secrets: inherit

  unittests:
    if: ${{ github.repository == 'envoyproxy/envoy' }}
    needs: env
    name: unit_tests
    runs-on: ubuntu-20.04
    timeout-minutes: 120
    container:
      image: ${{ needs.env.outputs.build_image_ubuntu }}
    steps:
    - uses: actions/checkout@v3
    - name: Ensure no listener leaks
      run: rm source/extensions/listener_managers/listener_manager/listener_manager_impl.h
    - name: Add safe directory
      run: git config --global --add safe.directory /__w/envoy/envoy
    - name: 'Run tests'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd mobile && ./bazelw test \
            --build_tests_only \
            --action_env=LD_LIBRARY_PATH \
            --test_env=ENVOY_IP_TEST_VERSIONS=v4only \
            --test_output=all \
            --define envoy_mobile_listener=disabled \
            $([ -z $GITHUB_TOKEN ] || echo "--config=remote-ci-linux") \
            //test/common/...
