name: mobile_docs

permissions:
  contents: read

on:
  push:
    branches:
    - main
  pull_request:

concurrency:
  group: ${{ github.head_ref || github.run_id }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  env:
    if: ${{ github.repository == 'envoyproxy/envoy' }}
    uses: ./.github/workflows/_env.yml
    permissions:
      contents: read
      pull-requests: read

  docs:
    if: ${{ github.repository == 'envoyproxy/envoy' }}
    needs: env
    permissions:
      contents: read
      packages: read
    runs-on: ${{ needs.env.outputs.agent_ubuntu }}
    timeout-minutes: 20
    steps:
    # Checkout the Envoy repo
    - uses: actions/checkout@v4
    # Checkout the envoy-mobile/envoy-mobile.github.io repo
    - uses: actions/checkout@v4
      with:
        repository: envoy-mobile/envoy-mobile.github.io
        path: mobile-docs
        fetch-depth: 0
        ssh-key: ${{ secrets.ENVOY_MOBILE_WEBSITE_DEPLOY_KEY }}
    - name: Add safe directory
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
    # Not sure if this is necessary
    - name: Add safe directory
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE/mobile-docs"
    - name: Generate docs
      run: ./ci/run_envoy_docker.sh 'cd mobile && docs/build.sh'
    - name: Publish docs
      run: ./ci/run_envoy_docker.sh 'cd mobile && docs/publish.sh'
      env:
        # Path relative to ./mobile directory
        MOBILE_DOCS_CHECKOUT_DIR: ../mobile-docs
    # This step needs to be done outside the container to access ssh creds
    - name: Push changes
      if: ${{ github.event_name != 'pull_request' }}
      run: |
        git -C mobile-docs push origin master

    - uses: actions/upload-artifact@v3
      with:
        name: docs
        path: mobile/generated/docs
