name: mobile_release_validation

permissions:
  contents: read

on:
  push:
    branches:
    - main
  pull_request:

concurrency:
  group: ${{ github.head_ref || github.run_id }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  env:
    if: ${{ github.repository == 'envoyproxy/envoy' }}
    uses: ./.github/workflows/_env.yml
    permissions:
      contents: read
      pull-requests: read

  validate_swiftpm_example:
    if: ${{ needs.env.outputs.mobile_release_validation == 'true' }}
    needs: env
    permissions:
      contents: read
      packages: read
    name: validate_swiftpm_example
    runs-on: macos-12
    timeout-minutes: 120
    steps:
    - uses: actions/checkout@v4
    - run: |
        cd mobile
        ./ci/mac_ci_setup.sh
      name: 'Install dependencies'
    - name: 'Build xcframework'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd mobile
        ./bazelw build \
            --config=ios \
            --config=mobile-remote-ci-macos \
            //:ios_xcframework
    # Ignore errors: Bad CRC when unzipping large files: https://bbs.archlinux.org/viewtopic.php?id=153011
    - run: |
        unzip mobile/bazel-bin/library/swift/Envoy.xcframework.zip \
              -d mobile/examples/swift/swiftpm/Packages \
            || :
      name: 'Unzip xcframework'
    - run: |
        xcodebuild -project mobile/examples/swift/swiftpm/EnvoySwiftPMExample.xcodeproj \
                   -scheme EnvoySwiftPMExample \
                   -destination platform="iOS Simulator,name=iPhone 14 Pro Max,OS=16.1"
      name: 'Build app'
    # TODO(jpsim): Run app and inspect logs to validate
