name: mobile_asan

on:
  push:
    branches:
    - main
  pull_request:

concurrency:
  group: ${{ github.head_ref-github.workflow || github.run_id }}
  cancel-in-progress: true

jobs:
  asan:
    if: github.repository == 'envoyproxy/envoy'
    name: asan
    runs-on: ubuntu-20.04
    timeout-minutes: 180
    container:
      image: envoyproxy/envoy-build-ubuntu:mobile-321658b6b50abda6869f89fac275f59bf3b1e757
      env:
        CC: /opt/llvm/bin/clang
        CXX: /opt/llvm/bin/clang++
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Add safe directory
      run: git config --global --add safe.directory /__w/envoy/envoy
    - id: should_run
      name: 'Check whether to run'
      run: ./mobile/tools/should_run_ci.sh
    - name: 'Run tests'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: steps.should_run.outputs.run_ci_job == 'true'
      run: |
        cd mobile && ./bazelw test --test_output=all \
            --test_env=ENVOY_IP_TEST_VERSIONS=v4only \
            $([ -z $GITHUB_TOKEN ] || echo "--config=remote-ci-linux-asan") \
            //test/common/...
