name: ios_tests

on:
  push:
    branches:
    - main
  pull_request:

concurrency:
  group: ${{ github.head_ref || github.run_id }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  env:
    if: ${{ github.repository == 'envoyproxy/envoy' }}
    uses: ./.github/workflows/env.yml
    secrets: inherit

  swifttests:
    if: ${{ needs.env.outputs.mobile_ios_tests == 'true' }}
    needs: env
    name: swift_tests
    runs-on: macos-12
    timeout-minutes: 120
    steps:
    - uses: actions/checkout@v3
    - name: 'Install dependencies'
      run: cd mobile && ./ci/mac_ci_setup.sh
    - name: 'Run swift library tests'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # runs with the listener enabled due to IdleTimeoutTest not setting up a test backend.
      run: |
        cd mobile && ./bazelw test \
            --experimental_ui_max_stdouterr_bytes=10485760 \
            --test_output=all \
            --config=ios \
            --define envoy_mobile_listener=enabled \
            --build_tests_only \
            $([ -z $GITHUB_TOKEN ] || echo "--config=remote-ci-macos") \
            //test/swift/...
  objctests:
    if: ${{ needs.env.outputs.mobile_ios_tests == 'true' }}
    needs: env
    name: c_and_objc_tests
    runs-on: macos-12
    timeout-minutes: 120
    steps:
    - uses: actions/checkout@v3
    - name: 'Install dependencies'
      run: cd mobile && ./ci/mac_ci_setup.sh
    - name: 'Run Objective-C library tests'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd mobile && ./bazelw test \
            --test_output=all \
            --config=ios \
            --build_tests_only \
            $([ -z $GITHUB_TOKEN ] || echo "--config=remote-ci-macos") \
            //test/objective-c/...  \
            //test/cc/unit:envoy_config_test
